<?php

namespace Tests\Feature\Unit\UserManagement;

use App\Models\User;
use Tests\TestCase;

class UserManagementTest extends TestCase
{
    private $user;

    protected function setUp(): void
    {
        parent::setUp();

        $user = User::create([
            'nome' => 'MOISES ABREU',
            'usuario' => 'moises.rodrigues',
            'setor_id' => 2,
            'nivel_id' => 1
        ]);

        auth()->login($user);

        $this->user = $user;
    }


    protected function tearDown(): void
    {
        auth()->logout();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testListAllUserWithPermissionBasic()
    {
        $this->get("admin/usuario/home")->assertStatus(302);
    }

}
