<?php

namespace Tests\Feature\Unit\Ouvidoria;

use App\Models\helpers;
use App\Models\Ouvidoria;
use Tests\TestCase;
use App\Models\User;

class OuvidoriaForwardTest extends TestCase
{
    private $user;

    protected function setUp(): void
    {
        parent::setUp();

        $user = User::create([
            'nome' => 'MOISES ABREU',
            'usuario' => 'moises.rodrigues',
            'setor_id' => 2,
            'nivel_id' => 2
        ]);

        auth()->login($user);

        $this->user = $user;
    }


    protected function tearDown(): void
    {
        auth()->logout();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testEncaminharOuvidoriaSucesso()
    {
        $form = $this->form();

        $ouvidoriaInstance = Ouvidoria::create($form->data);

        $ocorrenciaData = (object) [
            'data' => [
                'ocorrencia_id' => $ouvidoriaInstance->id,
                'status_ocorrencia_id' => 2,
                'setor_id' => 4
            ]
        ];

        $this->put('admin/ouvidoria/encaminhar', $ocorrenciaData->data);

        $this->assertDatabaseHas('ouvidoria_historico', [
                'ocorrencia_id' => $ocorrenciaData->data['ocorrencia_id'],
                'status_ocorrencia_id' => $ocorrenciaData->data['status_ocorrencia_id']
        ]);

        $ouvidoriaUpdatedInstance = Ouvidoria::where(['status_id' => $ocorrenciaData->data['status_ocorrencia_id'], 'setor_responsavel_id' => $ocorrenciaData->data['setor_id']])->get()->first();

        $this->assertTrue(!is_null($ouvidoriaUpdatedInstance));
    }

    private function form(){
        $protocol = new helpers();

        return (object) [
            'data' => [
                'protocolo' => $protocol->generateProtocol(2),
                'nome' => 'Moises abreu',
                'contato' => 'moises.rodrigues@unifametro.edu.br',
                'descricao' => 'Mussum Ipsum, cacilds vidis litro abertis. Sapien in monti palavris qui num significa nadis i pareci latim. Paisis, filhis, espiritis santis. Per aumento de cachacis, eu reclamis. Interagi no mé, cursus quis, vehicula ac nisi',
                'categoria_id' => 1,
                'demandante_id' => 2,
                'campus_id' => 5
            ],
        ];
    }


}
